version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
        # ports:
        #   - 9200:9200
    network_mode: host
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:8.5.3
#    restart: always
#    environment:
#      - ELASTICSEARCH_HOSTS=http://localhost:9200
#        # ports:
#        #   - 5601:5601
#    depends_on:
#      - elasticsearch
#    network_mode: host

